# Generated by Django 5.0 on 2024-12-18 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
